return {
	Attributes = {
		ty = "Attributes",
		value = {
			Attributes = {
				TestBool = {
					Bool = true,
				},
				TestBrickColor = {
					BrickColor = 24,
				},
				TestColor3 = {
					Color3 = {1, 0.5, 0},
				},
				TestNumber = {
					Float64 = 1337,
				},
				TestRect = {
					Rect = {{1, 2}, {3, 4}},
				},
				TestString = {
					String = "Test",
				},
				TestUDim = {
					UDim = {1, 2},
				},
				TestUDim2 = {
					UDim2 = {{1, 2}, {3, 4}},
				},
				TestVector2 = {
					Vector2 = {1, 2},
				},
				TestVector3 = {
					Vector3 = {1, 2, 3},
				},
			},
		},
	},
	Axes = {
		ty = "Axes",
		value = {
			Axes = {"X", "Y", "Z"},
		},
	},
	BinaryString = {
		ty = "BinaryString",
		value = {
			BinaryString = "SGVsbG8h",
		},
	},
	Bool = {
		ty = "Bool",
		value = {
			Bool = true,
		},
	},
	BrickColor = {
		ty = "BrickColor",
		value = {
			BrickColor = 1004,
		},
	},
	CFrame = {
		ty = "CFrame",
		value = {
			CFrame = {
				orientation = {{4, 5, 6}, {7, 8, 9}, {10, 11, 12}},
				position = {1, 2, 3},
			},
		},
	},
	Color3 = {
		ty = "Color3",
		value = {
			Color3 = {1, 2, 3},
		},
	},
	Color3uint8 = {
		ty = "Color3uint8",
		value = {
			Color3uint8 = {0, 128, 255},
		},
	},
	ColorSequence = {
		ty = "ColorSequence",
		value = {
			ColorSequence = {
				keypoints = {{
					color = {1, 1, 0.5},
					time = 0,
				}, {
					color = {0, 0, 0},
					time = 1,
				}},
			},
		},
	},
	Content = {
		ty = "Content",
		value = {
			Content = "rbxassetid://12345",
		},
	},
	Enum = {
		ty = "Enum",
		value = {
			Enum = 1234,
		},
	},
	Faces = {
		ty = "Faces",
		value = {
			Faces = {"Right", "Top", "Back", "Left", "Bottom", "Front"},
		},
	},
	Float32 = {
		ty = "Float32",
		value = {
			Float32 = 15,
		},
	},
	Float64 = {
		ty = "Float64",
		value = {
			Float64 = 15123,
		},
	},
	Int32 = {
		ty = "Int32",
		value = {
			Int32 = 6014,
		},
	},
	Int64 = {
		ty = "Int64",
		value = {
			Int64 = 23491023,
		},
	},
	NumberRange = {
		ty = "NumberRange",
		value = {
			NumberRange = {-36, 94},
		},
	},
	NumberSequence = {
		ty = "NumberSequence",
		value = {
			NumberSequence = {
				keypoints = {{
					envelope = 2,
					time = 0,
					value = 5,
				}, {
					envelope = 0,
					time = 1,
					value = 22,
				}},
			},
		},
	},
	["PhysicalProperties-Custom"] = {
		ty = "PhysicalProperties",
		value = {
			PhysicalProperties = {
				density = 0.5,
				elasticity = 0,
				elasticityWeight = 25,
				friction = 1,
				frictionWeight = 50,
			},
		},
	},
	["PhysicalProperties-Default"] = {
		ty = "PhysicalProperties",
		value = {
			PhysicalProperties = "Default",
		},
	},
	Ray = {
		ty = "Ray",
		value = {
			Ray = {
				direction = {4, 5, 6},
				origin = {1, 2, 3},
			},
		},
	},
	Rect = {
		ty = "Rect",
		value = {
			Rect = {{0, 5}, {10, 15}},
		},
	},
	Region3int16 = {
		ty = "Region3int16",
		value = {
			Region3int16 = {{-10, -5, 0}, {5, 10, 15}},
		},
	},
	String = {
		ty = "String",
		value = {
			String = "Hello, world!",
		},
	},
	Tags = {
		ty = "Tags",
		value = {
			Tags = {"foo", "con'fusion?!", "bar"},
		},
	},
	UDim = {
		ty = "UDim",
		value = {
			UDim = {1, 32},
		},
	},
	UDim2 = {
		ty = "UDim2",
		value = {
			UDim2 = {{-1, 100}, {1, -100}},
		},
	},
	Vector2 = {
		ty = "Vector2",
		value = {
			Vector2 = {-50, 50},
		},
	},
	Vector2int16 = {
		ty = "Vector2int16",
		value = {
			Vector2int16 = {-300, 300},
		},
	},
	Vector3 = {
		ty = "Vector3",
		value = {
			Vector3 = {-300, 0, 1500},
		},
	},
	Vector3int16 = {
		ty = "Vector3int16",
		value = {
			Vector3int16 = {60, 37, -450},
		},
	},
}